### ISSUE TITLE
出现zeroclipboard问题

### ISSUE THREAD

**Issue by xgj1988** [uso51984/react-ueditor#2]
×
ReferenceError: ZeroClipboard is not defined
initZeroClipboard
E:/workspace/gitlab_repo/manager-xyzy-antd/public/js/ueditor/ueditor.all.js:14455

**Comment by lxtzxd** [comment]
解决了吗？我也碰到这个问题了，好像是因为ZeroClipboard 不是模块化的导致的

**Comment by xgj1988** [comment]
搞定了，，路径位置不对。

**Comment by lxtzxd** [comment]
请问你怎么改的，我也试试

**Comment by xgj1988** [comment]
@lxtzxd  我该的ueditor.config.js文件。。var URL = window.UEDITOR_HOME_URL || getUEBasePath() + 'js/ueditor/';
后面是我加的。。你根据你的路径来加吧。

**Comment by xgj1988** [comment]
@lxtzxd  我这便有出问题了，。你搞定了吗？
